# Generated by Django 5.0.6 on 2024-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
