# Generated by Django 5.0.6 on 2024-06-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otp_otp_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='otp',
        ),
    ]
