# Generated by Django 5.0.6 on 2024-06-18 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_otp_alter_otp_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='accounts.userprofile'),
        ),
    ]
